config/routes.rb
Dashboard::Application.routes.draw do
  get "dashboard/index"
  get "dashboard/lists"
  get "dashboard/wiki"

  root :to => 'dashboard#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  caches_page :lists, :expires_in => 15.minutes
  caches_page :index, :expires_in => 15.minutes
  caches_page :wiki, :expires_in => 15.minutes
  
  def index
  end

  def lists
  end

  def wiki
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def last_threads_list(list_name)
    archive_url = "http://lists.piratenfraktion-nrw.de/pipermail/#{list_name}/"
    @doc = Nokogiri::HTML(open(archive_url)) if @doc.nil?
    current_thread_url = @doc.css("table tr:nth-child(2) td:nth-child(2) a:first-child").first["href"]
    @thread_doc = Nokogiri::HTML(open(archive_url + "/#{current_thread_url}")) rescue []

    @thread_doc.css("html body ul li a").map { |el| "<a href='#{archive_url + current_thread_url.gsub(/thread\.html/,'') + el["href"]}'>#{truncate(el.text.scan(/\[.*\](.*)/).flatten.first, :length => 25)}</a>" if el.text.length > 5 }.compact[4..8] rescue []
  end
end

app/views/dashboard/_mailinglist.html.erb
<h4><%= list_name %></h4>
<ul>
  <% last_threads_list(list_name).each do |thread| %>
    <li><%= thread.html_safe %></li>
  <% end %>
</ul>

app/views/dashboard/index.html.erb
<div class="row-fluid">
  <div class="span3">
    <h4>Adressbuch</h4>
    <div class="well">
      Das zentrale Adressbuch. Der eigene Eintrag kann mit dem Account Editor bearbeitet werden.
      <br/><br/><br/><br/>
      <a class="btn btn-primary" href="https://account.piratenfraktion-nrw.de/address_book/show">Zum Adressbuch</a>
    </div>
  </div>
  <div class="span3">
    <h4>Zimbra/Webmail</h4>
    <div class="well">
      Unser E-Mailsystem, darüber kannst du E-Mails, Kalender und Kontakte verwalten.
      <br/><br/><br/><br/>
      <a class="btn btn-primary" href="https://webmail.piratenfraktion-nrw.de">Webmailer aufrufen</a>
    </div>
  </div>
  <div class="span3">
    <h4>Wiki</h4>
    <div class="well">
      In unserem Wiki findest du Protokolle, Anleitungen und viele andere speicherwürdige Dinge.
      <br/><br/><br/><br/>
      <a class="btn btn-primary" href="https://wiki.piratenfraktion-nrw.de">Zum Wiki</a>
    </div>
  </div>
  <div class="span3">
    <h4>Redmine</h4>
    <div class="well">
      Redmine ist eine Projekt- und Aufgabenverwaltungsanwendung.
      Außerdem sind dort Aktuelle Umlaufbeschlüsse und anderes zu sehen.
      <br/><br/><br/>
      <a class="btn btn-primary" href="https://redmine.piratenfraktion-nrw.de">Zum Redmine</a>
    </div>
  </div>
</div>
<div class="row-fluid">
  <div class="span3">
    <h4>Pad</h4>
    <div class="well">
      Über das Pad können viele Menschen gleichzeitig an einem Text arbeiten.
      Pads sind nicht zur dauerhaften Speicherung geeignet, überführt wichtige Pads anschließend bitte ins Wiki.
      <br/><br/>
      <a class="btn btn-primary" href="https://pad.piratenfraktion-nrw.de">Zum neuen Pad</a>
    </div>
  </div>
  <div class="span3">
    <h4>Blog/Website</h4>
    <div class="well">
      Die Fraktionswebsite. Die Pressestelle ist für die Inhalte zuständig.
      <br/><br/><br/><br/>
      <a class="btn btn-primary" href="https://www.piratenfraktion-nrw.de">Zur Website</a>
      <a class="btn btn-primary" href="https://www.piratenfraktion-nrw.de/wp-admin/">Zum Blog-Dashboard</a>
    </div>
  </div>
  <div class="span3">
    <h4>Account Editor</h4>
    <div class="well">
      Mit dem Account Editor kannst du deinen Eintrag im Fraktionsadressbuch bearbeiten.
      Bitte achte darauf, dass dein Eintrag möglichst vollständig ist.
      <br/><br/><br/>
      <a class="btn btn-primary" href="https://account.piratenfraktion-nrw.de">Zum Account Editor</a>
    </div>
  </div>
  <div class="span3">
    <h4>Jabber</h4>
    <div class="well">
      Jabber ist ein Kurznachrichtendienst über den man einfach und schnell mit Menschen in Kontakt treten kann.
      Auf Landtagshardware muss leider der Weblclient benutzt werden, allen anderen empfehlen wir Pidgin.
      <br/><br/>
      <a class="btn btn-primary" href="https://jappix.piratenfraktion-nrw.de">Zum Webclient</a>
      <a class="btn btn-primary" href="https://wiki.piratenfraktion-nrw.de/wiki/HowTo:IT/Jabber">Anleitung</a>
    </div>
  </div>
</div>
<div class="row-fluid">
  <div class="span3">
    <h4>Owncloud</h4>
    <div class="well">
      Über die Owncloud kann man Dateien hochladen, die dann mit anderen geteilt werden können.
      <br/><br/><br/><br/>
      <a class="btn btn-primary" href="https://cloud.piratenfraktion-nrw.de">Zur Owncloud</a>
    </div>
  </div>
<div class="span3">
    <h4>Mailinglisten</h4>
    <div class="well">
      Die öffentlichen Diskussionslisten der Fraktion.
      <br/><br/><br/><br/><br/>
      <a class="btn btn-primary" href="https://lists.piratenfraktion-nrw.de">Zur Übersicht</a>
    </div>
  </div>
  <div class="span3">
    <h4>Sonstiges</h4>
    <div class="well">
      <ul>
        <li><a href="https://wiki.piratenfraktion-nrw.de/wiki/Kategorie:Infototholz">Infotothölzer im Wiki</a></li>
        <li><a href="https://wiki.piratenfraktion-nrw.de/wiki/Kategorie:Protokoll">Protokolle im Wiki</a></li>
        <li><a href="http://antragsfabrik.de" title="Antragsfabrik bei OpenAntrag">Antragsfabrik der Fraktion bei OpenAntrag</a></li>
        <li><a href="https://timer.piratenfraktion-nrw.de" title="FraSiTimer">FraSiTimer</a></li>
      </ul>
      <p>
        Sonstige Anleitungen und Hilfeseite im <a href="https://wiki.piratenfraktion-nrw.de/">Wiki</a>
      </p>
    </div>
  </div>
  <!--div class="span3">
    <h4>Account Editor</h4>
    <div class="well">
      Mit dem Account Editor kannst du deinen Eintrag im Fraktionsadressbuch bearbeiten.
      Bitte achte darauf, dass dein Eintrag möglichst vollständig ist.
      <br/><br/><br/>
      <a class="btn btn-primary" href="https://account.piratenfraktion-nrw.de">Zum Account Editor</a>
    </div>
  </div>
  <div class="span3">
    <h4>Sonstiges</h4>
    <div class="well">
      <ul>
        <li><a href="https://wiki.piratenfraktion-nrw.de/images/c/c7/Infototholz.pdf">Infototholz</a></li>
        <li><a href="https://wiki.piratenfraktion-nrw.de/wiki/Kategorie:Protokoll">Protokolle im Wiki</a></li>
      </ul>
      <p>
        Sonstige Anleitungen und Hilfeseite im <a href="https://wiki.piratenfraktion-nrw.de/">Wiki</a>
      </p>
    </div>
  </div -->
</div>

app/views/dashboard/lists.html.erb
<div class="row">
  <h3 id="lists-header">Mailinglisten</h3>
  <div id="lists" class="span9">
    <div class="row">
      <div class="span3">
        <%= render :partial => "mailinglist", :locals => { :list_name => "20piraten" } %> 
      </div>
      <div class="span3">
        <%= render :partial => "mailinglist", :locals => { :list_name => "20piraten-info" } %> 
      </div>
      <div class="span3">
        <%= render :partial => "mailinglist", :locals => { :list_name => "fraktionen-europa" } %> 
      </div>
    </div>
    <div class="row">
      <div class="span4">
        <%= render :partial => "mailinglist", :locals => { :list_name => "pm" } %> 
      </div>
    </div>
  </div>
</div>

app/views/dashboard/wiki.html.erb
<div class="row">
<div class="span5">
  <h3>Piratenfraktion NRW &dash; Dashboard</h3>
  <p>
    Willkommen auf der Startseite der Piratenfraktion NRW.
  </p>
  <p>
    Hier findest du Übersichten zu den wichtigsten Fraktionsdiensten. Benutze das Menü am linken Rand um einen Bereich aufzurufen.
  </p>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dashboard" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Dashboard</a>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span4 offset4">
          <%= image_tag "logo.png" %>
        </div>
      </div>
      <div class="row-fluid">
        <% if controller.action_name != "index" %>
          <div class="span3">
            <div class="well sidebar-nav">
              <ul class="nav nav-list">
                <li class="nav-header">Meü</li>
                <li><%= link_to "Start", "/"  %></li>
                <li><%= link_to "Mailinglisten", dashboard_lists_path  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        <% else %>
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        <% end %>
      </div><!--/row-->

      <footer>
        <p>Piratenfraktion im Landtag NRW</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

    <!-- Piwik --> 
    <script type="text/javascript">
      var pkBaseURL = (("https:" == document.location.protocol) ? "https://piwik.piratenfraktion-nrw.de/" : "http://piwik.piratenfraktion-nrw.de/");
      document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
      </script><script type="text/javascript">
      try {
        var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 8);
        piwikTracker.trackPageView();
        piwikTracker.enableLinkTracking();
      } catch( err ) {}
    </script><noscript><p><img src="https://piwik.piratenfraktion-nrw.de/piwik.php?idsite=8" style="border:0" alt="" /></p></noscript>
    <!-- End Piwik Tracking Code -->
  </body>
</html>